GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/1
###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Maryum Hamid",
    "number": "40-354-4561"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Maryum Hamid",
    "number": "40-354-4561"
}

DELETE http://localhost:3001/api/persons/100
###
GET http://localhost:3001/api/persons/100